// export const suggestions = [
//   {
//     title: 'Olde Nola Cookery',
//     upVotes: 0,
//     downVotes: 0,
//     description: 'Cooked by Locals, Spiced with History\" Located on the famous Bourbon Street in the heart of the French Quarter. Come take it all in... the sights, the sounds and the taste of New Orleans!',
//     image: "https://media-cdn.tripadvisor.com/media/photo-s/15/17/12/7f/seafood-platter.jpg",
//     phoneNum: '+1 504-525-4577',
//     address: '205 Bourbon St, New Orleans, LA 70130-2204',
//     latitude: "29.954908",
//     longitude: "-90.06912",
//     hours: "Monday: 11:00 - 01:00",
//           // "Tuesday: 11:00 - 01:00":
//           // "Wednesday: 11:00 - 01:00",
//           // "Thursday: 11:00 - 01:00":
//           // "Friday: 11:00 - 01:00",
//           // "Saturday: 11:00 - 01:00":
//           // "Sunday: 11:00 - 01:00",
//     userId: null,
//   },
//   {
//     title: "Melba's Po Boys",
//     upVotes: 0,
//     downVotes: 0,
//     description: "2016 Inc 500 magazine as one of the fastest growing companies in US 2017 GQ magazine as one of the best restaurants in America 2018 Entrepreneur Magazine as one of the best run businesses 2019 Forbes publishes biography of founders Jane and Scott Wolfe (GED to Harvard and then INC 500) available Amazon & Barnes/Nobles 2020 Fast Company magazine award: World changing businesses",
//     image: "https://media-cdn.tripadvisor.com/media/photo-s/17/37/f8/3c/outside.jpg",
//     phoneNum: "+1 504-267-7765",
//     address: "1525 Elysian Fields Ave 5 min from French Quarter, New Orleans, LA 70117-8207",
//     latitude: "29.973034",
//     longitude: "-90.05646",
//     hours: [
//       "Monday: 00:00 - 23:59",
//       "Tuesday: 00:00 - 23:59",
//       "Wednesday: 00:00 - 23:59",
//       "Thursday: 00:00 - 23:59",
//       "Friday: 00:00 - 23:59",
//       "Saturday: 00:00 - 23:59",
//       "Sunday: 00:00 - 23:59"
//   ],
//     userId: null,
    
//   },
//   {
//     title: "Vaughan's Lounge",
//     upVotes: 0,
//     downVotes: 0,
//     description: "This small bar is a hot spot for live jazz and has free soul food and cheap drinks. Closed due to damage suffered in Hurricane Katrina.",
//     image: "https://media-cdn.tripadvisor.com/media/photo-s/17/60/c0/7e/photo0jpg.jpg",
//     phoneNum:  "+1 504-947-5562",
//     address: "4229 Dauphine St, New Orleans, LA 70117",
//     latitude: "29.96195",
//     longitude: "-90.03372",
//     hours: //[
//       "Monday: 12:00 - 00:00",
//       // "Tuesday: 12:00 - 00:00",
//       // "Wednesday: 12:00 - 00:00",
//       // "Thursday: 12:00 - 00:00",
//       // "Friday: 12:00 - 00:00",
//       // "Saturday: 12:00 - 00:00",
//       // "Sunday: 12:00 - 00:00"
//  // ],
//     userId: null,
//   },
//   {
//     title: "Blue Nile",
//     upVotes: 0,
//     downVotes: 0,
//     description: "description not found",
//     image: "https://media-cdn.tripadvisor.com/media/photo-s/0d/2e/68/23/great-local-music.jpg",
//     phoneNum: "+1 504-948-2583",
//     address: "532 Frenchmen St, New Orleans, LA 70116-2024",
//     latitude: "29.963223",
//     longitude: "-90.05775",
//     hours: "no hours specified",
//     userId: null,
//   },
//   {
//     title: "The National WWII Museum",
//     upVotes: 0,
//     downVotes: 0,
//     description: "The National WWII Museum is the top-rated tourist destination in New Orleans and #2 in the U.S., and an unforgettable way to experience World War II—from industrial efforts on the home front to the combat experience of the American servicemember abroad. Offering a compelling blend of sweeping narrative and poignant personal detail, the Museum features immersive exhibits, multimedia experiences, and an expansive collection of artifacts and first-person oral histories to take visitors inside the story of the war: why it was fought, how it was won, and what it means today. Beyond the galleries, the Museum offers unique access to experiential history, including an opportunity to tour and ride on an authentically restored PT-boat, tours behind the scenes to handle artifacts alongside Museum curators, and an impressive collection of restored and working macro-artifacts to discover. Open early through 1/2/18, 8:30 a.m.-5:00 p.m." ,
//     image: "https://media-cdn.tripadvisor.com/media/photo-s/04/18/68/e5/the-national-wwii-museum.jpg",
//     phoneNum: "+1 504-528-1944",
//     address: "945 Magazine Street, New Orleans, LA 70130-3813",
//     latitude: "29.94282",
//     longitude: "-90.07079",
//     hours: [
//       "Monday: 09:00 - 17:00",
//       "Tuesday: 09:00 - 17:00",
//       "Wednesday: 09:00 - 17:00",
//       "Thursday: 09:00 - 17:00",
//       "Friday: 09:00 - 17:00",
//       "Saturday: 09:00 - 17:00",
//       "Sunday: 09:00 - 17:00"
//   ],
//     userId: null,
//   },
//   {
//     title: "New Orleans Museum of Art",
//     upVotes: 0,
//     downVotes: 0,
//     description: "NOMA is committed to preserving, presenting, and enriching its collections and renowned Sydney and Walda Besthoff Sculpture Garden; offering innovative experiences for learning and interpretation; and uniting, inspiring, and engaging diverse communities and cultures. NOMA is New Orleans’ oldest fine arts institution and most ambitious cultural convener. NOMA’s permanent collection is at the heart of all museum programs and has grown from 13 works in 1912 to more than 40,000 today.",
//     image: "https://media-cdn.tripadvisor.com/media/photo-s/04/7d/e0/22/new-orleans-museum-of.jpg",
//     phoneNum: "+1 504-658-4100",
//     address: "1 Collins Diboll Cir, New Orleans, LA 70124-4605",
//     latitude: "29.986471",
//     longitude: "-90.09345",
//     hours:  [
//       "Monday: Closed",
//       "Tuesday: 10:00 - 17:00",
//       "Wednesday: 12:00 - 19:00",
//       "Thursday: 10:00 - 17:00",
//       "Friday: 10:00 - 17:00",
//       "Saturday: 10:00 - 17:00",
//       "Sunday: 10:00 - 17:00"
//   ],
//     userId: null,
//   },
//   {
//     upVotes: 0,
//     downVotes: 0,
//     title: "New Orleans Jazz Museum",
//     description: "The New Orleans Jazz Museum celebrates jazz in the city where it was born. Through dynamic interactive exhibits, multigenerational educational programming, reaserch facilities, and engaging musical performances, the music New Orleans made famous is explored in all its forms. Housed in the historic Old U.S. Mint, strategically located at the intersection of the French Quarter and the Frenchmen Street live music corridor, the New Orleans Jazz Museum is in the heart of the city’s music scene. Through partnerships with local, national, and international educational institutions, the New Orleans Jazz Museum promotes the global understanding of jazz as one of the most innovative, historically pivotal musical art forms in world history.",
//     image:  "https://media-cdn.tripadvisor.com/media/photo-s/0b/92/b7/85/20160608-102742-largejpg.jpg",
//     phoneNum: "+1 504-568-6993",
//     address:  "400 Esplanade Ave, New Orleans, LA 70116-2015",
//     latitude: "29.9614",
//     longitude: "-90.05782",
//     hours: [
//       "Monday: Closed",
//       "Tuesday: 10:00 - 16:30",
//       "Wednesday: 10:00 - 16:30",
//       "Thursday: 10:00 - 16:30",
//       "Friday: 10:00 - 16:30",
//       "Saturday: 10:00 - 16:30",
//       "Sunday: 10:00 - 16:30"
//   ],
//     userId: null,
//   }
// ]